### ISSUE TITLE
Color parsing is broken of VAR's with underscores - new in R48

### ISSUE THREAD

**Issue by jakebullet70** [Thraka/basload-lang#1]
The latest version of BASLOAD in R48 adds underscores as valid for var names. Look at vars FILE_TO_COMP$ and KBBUFFER_OUT

![image](https://github.com/user-attachments/assets/57208841-f097-4e03-9e1b-3eb3cddeacb0)

**Comment by jakebullet70** [comment]
Also just noticed the LINE LABEL has the same issue

**Comment by Thraka** [comment]
I'll look into it! Thanks!

**Comment by Thraka** [comment]
Fixed with version 1.1.1
