### ISSUE TITLE
Color formatting is off

### ISSUE THREAD

**Issue by jakebullet70** [Thraka/basload-lang#2]
![image](https://github.com/user-attachments/assets/290cd327-75e1-4e77-9421-25317c30014e)

```
   rem midway campaign
##    poke 53280,6:poke 53281,1
    PRINT "{clr}"
##	{down}{down}{down}{down}{down}{down}{down}{down}{down}{blk}"; TAB(8);"{rvon}                       "
    PRINT TAB(8);"{rvon} ** MIDWAY CAMPAIGN ** ":pi=~/180
```

**Comment by Thraka** [comment]
@jakebullet70 Can you check that your code compiles like that? You actually have a hard tab in there after the `##` and the color parser was looking for at least 1 space. I can tell it to also allow tabs in there, but does the actual BASLOAD compiler care about tabs vs spaces?

**Comment by Thraka** [comment]
Fixed!
